[variables]
NIXPACKS_NODE_VERSION = "18"

[phases.setup]
nixPkgs = ["nodejs_18", "npm-9_x"]

[phases.build]
cmds = ["npm ci", "npm run build"]

[phases.start]
cmd = "npm run start"

[variables]
PORT = "3000" 