[variables]
NIXPACKS_NODE_VERSION = "18"
PORT = "3000"

[phases.setup]
nixPkgs = ["nodejs_18", "npm-9_x"]

[phases.build]
cmds = ["npm install", "npm run build"]

[phases.start]
cmd = "npm run start" 