[variables]
  NODE_ENV = "production"

[phases.setup]
  nixPkgs = ['nodejs_18', 'npm']

[phases.install]
  dependsOn = ['setup']
  cmds = ['cd backend && npm ci']

[phases.build]
  dependsOn = ['install'] 
  cmds = ['cd backend && npm run build --if-present']

[start]
  cmd = 'cd backend && npm start' 